apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.97.128.117
  environments:
  - key: dev
    owner: valentinb-sixense
    repository: testjx
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: valentinb-sixense
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
